CREATE TABLE STUDENTS(
    student_id NUMBER PRIMARY KEY,
    student_name VARCHAR2(40),
    student_address VARCHAR2(45),
    student_age NUMBER,
    joined_date DATE
);

CREATE SEQUENCE sys.PRODUCT_SEQ 
    INCREMENT BY 1 
    START WITH 1 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE sys.CATEGORY_SEQ 
    INCREMENT BY 1 
    START WITH 1 
    NOCACHE 
    NOCYCLE;

DROP SEQUENCE sys.PRODUCT_SEQ;

SELECT SEQUENCE_OWNER, SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'CATEGORY_SEQ';

GRANT CREATE ANY SEQUENCE, SELECT ANY SEQUENCE TO system;
GRANT SELECT, ALTER ON sys.PRODUCT_SEQ TO system;

select * from sys.students;

GRANT CONNECT, RESOURCE TO sys;
GRANT CREATE SESSION TO sys;
GRANT CREATE TABLE TO sys;
GRANT CREATE SEQUENCE TO sys;
GRANT CREATE VIEW TO sys;
GRANT CREATE PROCEDURE TO sys;
GRANT UNLIMITED TABLESPACE TO sys;
GRANT INSERT, SELECT, UPDATE, DELETE ON CATEGORIES TO system;
