CREATE TABLE Comments(
    blog_id NUMBER PRIMARY KEY,
    title VARCHAR2(40),
    published_date DATE
);
CREATE TABLE Comments(
    comment_id NUMBER PRIMARY KEY,
    content VARCHAR2(40),
    is_approved VARCHAR(20),
    blog_id NUMBER REFERENCES Comments
);

Drop table Comments;


CREATE SEQUENCE sys.Comments_SEQ 
    INCREMENT BY 1 
    START WITH 1 
    NOCACHE 
    NOCYCLE;

-- DROP SEQUENCE sys.STUDENTS_SEQ;

SELECT SEQUENCE_OWNER, SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'sys.Comments_SEQ';

GRANT CREATE ANY SEQUENCE, SELECT ANY SEQUENCE TO system;
GRANT SELECT, ALTER ON sys.Comments_SEQ TO system;

select * from sys.Blogs;

GRANT CONNECT, RESOURCE TO sys;
GRANT CREATE SESSION TO sys;
GRANT CREATE TABLE TO sys;
GRANT CREATE SEQUENCE TO sys;
GRANT CREATE VIEW TO sys;
GRANT CREATE PROCEDURE TO sys;
GRANT UNLIMITED TABLESPACE TO sys;
GRANT INSERT, SELECT, UPDATE, DELETE ON Comments TO system;
